{block name='fh_region_detail'}
<main class="ru-discovery ru-region-detail">
    <section class="ru-region-hero">
        <div class="ru-container">
            <a class="ru-region-hero__back" href="{$fh_region_list_url|escape:'html':'UTF-8'}">{l s='All regions' mod='fhregions'}</a>
            <div class="ru-region-hero__grid">
                <div><p class="ru-eyebrow">{l s='Uttar Pradesh region' mod='fhregions'}</p><h1>{$fh_region->name|escape:'html':'UTF-8'}</h1><p>{$fh_region->blurb|escape:'html':'UTF-8'}</p></div>
                {if $fh_region->cover}<img src="{$smarty.const._PS_IMG_}fhregions/{$fh_region->cover|escape:'html':'UTF-8'}" alt="{$fh_region->name|escape:'html':'UTF-8'}">{/if}
            </div>
        </div>
    </section>
    {if $fh_region->description}<section class="ru-region-prose"><div class="ru-container"><div>{$fh_region->description}</div></div></section>{/if}
    <section class="ru-region-section"><div class="ru-container"><header class="ru-section-head"><div><p class="ru-eyebrow">{l s='Stay here' mod='fhregions'}</p><h2>{l s='Farmstays in %s' sprintf=[$fh_region->name|escape:'html':'UTF-8'] mod='fhregions'}</h2></div><a class="ru-link" href="{$fh_properties_url|escape:'html':'UTF-8'}">{l s='All farmstays' mod='fhregions'}</a></header>
        {if isset($fh_region_hotels) && $fh_region_hotels|@count}<div class="ru-region-property-list">{foreach $fh_region_hotels as $hotel}<article>{if $hotel.image_url|default:''}<a class="ru-region-property-list__media" href="{$hotel.property_link|escape:'html':'UTF-8'}"><img loading="lazy" src="{$hotel.image_url|escape:'html':'UTF-8'}" alt="{$hotel.hotel_name|escape:'html':'UTF-8'}"></a>{/if}<p class="ru-eyebrow">{if $hotel.city}{$hotel.city|escape:'html':'UTF-8'}{/if}</p><h3>{$hotel.hotel_name|escape:'html':'UTF-8'}</h3>{if $hotel.short_description}<p>{$hotel.short_description|strip_tags|truncate:105:'...'|escape:'html':'UTF-8'}</p>{/if}{if $hotel.rating}<p>{l s='Rated' mod='fhregions'} {$hotel.rating|intval}/5</p>{/if}<p class="ru-demo-disclosure">{l s='Demo stay · representative imagery' mod='fhregions'}</p><a class="ru-link" href="{if $hotel.property_link}{$hotel.property_link|escape:'html':'UTF-8'}{else}{$fh_properties_url|escape:'html':'UTF-8'}{/if}">{l s='View farmhouse' mod='fhregions'}</a></article>{/foreach}</div>{else}<p class="ru-empty-state">{l s='Farmstays in this region are being added. Browse the full list of stays.' mod='fhregions'} <a href="{$fh_properties_url|escape:'html':'UTF-8'}">{l s='Browse all stays' mod='fhregions'}</a></p>{/if}
    </div></section>
    {if isset($fh_region_activities) && $fh_region_activities|@count}<section class="ru-region-section ru-region-section--sage"><div class="ru-container"><header class="ru-section-head"><div><p class="ru-eyebrow">{l s='Local rhythm' mod='fhregions'}</p><h2>{l s='Things to do in %s' sprintf=[$fh_region->name|escape:'html':'UTF-8'] mod='fhregions'}</h2></div>{if $fh_activities_url}<a class="ru-link" href="{$fh_activities_url|escape:'html':'UTF-8'}">{l s='All activities' mod='fhregions'}</a>{/if}</header><div class="ru-region-activity-list">{foreach $fh_region_activities as $activity}<article>{if $activity.category}<p class="ru-eyebrow">{$activity.category|escape:'html':'UTF-8'}</p>{/if}<h3>{$activity.name|escape:'html':'UTF-8'}</h3><p>{$activity.short_description|escape:'html':'UTF-8'}</p>{if $activity.typical_duration}<span>{$activity.typical_duration|escape:'html':'UTF-8'}</span>{/if}</article>{/foreach}</div></div></section>{/if}
    {if isset($fh_region_adjacent) && ($fh_region_adjacent.prev || $fh_region_adjacent.next)}<nav class="ru-region-adjacent ru-container">{if $fh_region_adjacent.prev}<a href="{$fh_region_detail_url|escape:'html':'UTF-8'}&id_region={$fh_region_adjacent.prev.id_region|intval}">{l s='Previous' mod='fhregions'}: {$fh_region_adjacent.prev.name|escape:'html':'UTF-8'}</a>{/if}{if $fh_region_adjacent.next}<a href="{$fh_region_detail_url|escape:'html':'UTF-8'}&id_region={$fh_region_adjacent.next.id_region|intval}">{l s='Next' mod='fhregions'}: {$fh_region_adjacent.next.name|escape:'html':'UTF-8'}</a>{/if}</nav>{/if}
</main>
{/block}
