#!/usr/bin/env bash
# Boots the QloApps demo stack inside a GitHub Codespace.
# Idempotent: safe to re-run after `git pull` to refresh the demo.
# Usage: bash scripts/deploy-codespaces.sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

COMPOSE=(docker compose -f docker-compose.yml -f docker-compose.codespaces.yml)

if ! command -v docker >/dev/null 2>&1; then
    echo "docker is not available in this Codespace." >&2
    exit 1
fi

# 1. Make the MariaDB 11.x seed dump compatible with the pinned mariadb:10.11
#    image (utf8mb3_uca1400_ai_ci does not exist on 10.11). The tracked
#    db/init file is left untouched; the converted copy lives in the
#    gitignored db/init-converted dir that the compose override mounts.
INIT_SRC=db/init/01-init.sql
INIT_DST=db/init-converted/01-init.sql
if [ ! -f "$INIT_SRC" ]; then
    echo "Missing seed dump: $INIT_SRC. Push it to the repo first." >&2
    exit 1
fi
mkdir -p "$(dirname "$INIT_DST")"
sed -e 's/utf8mb4_uca1400_ai_ci/utf8mb4_general_ci/g' \
    -e 's/utf8mb3_uca1400_ai_ci/utf8mb3_general_ci/g' \
    "$INIT_SRC" > "$INIT_DST"
if grep -q uca1400 "$INIT_DST"; then
    echo "Collation conversion incomplete; aborting." >&2
    exit 1
fi
if [ ! -s "$INIT_DST" ]; then
    echo "Converted seed dump is empty; aborting." >&2
    exit 1
fi

# 2. Generate .env on first run. Never commit it.
DEFUSE_PHAR=tools/defuse/php-encryption/defuse-crypto.phar
if ! command -v php >/dev/null 2>&1; then
    echo "php is not available in this Codespace; cannot generate a valid Defuse NEW_COOKIE_KEY." >&2
    exit 1
fi
if [ ! -f "$DEFUSE_PHAR" ]; then
    echo "Missing $DEFUSE_PHAR; cannot generate a valid Defuse NEW_COOKIE_KEY." >&2
    exit 1
fi

make_cookie_key() {
    php -r 'require $argv[1]; echo Defuse\Crypto\Key::createNewRandomKey()->saveToAsciiSafeString();' "$DEFUSE_PHAR"
}

if [ ! -f .env ]; then
    cat > .env <<EOF
# Generated by scripts/deploy-codespaces.sh - local to this Codespace only.
DB_NAME=qloapps
DB_USER=qloapps
DB_PASSWD=$(openssl rand -hex 12)
MARIADB_ROOT_PASSWORD=$(openssl rand -hex 12)
DB_PREFIX=qlo_
HTTP_PORT=8080
SHOP_DOMAIN=localhost:8080
COOKIE_KEY=$(openssl rand -hex 24)
COOKIE_IV=$(openssl rand -hex 4)
NEW_COOKIE_KEY=$(make_cookie_key)
EOF
fi

# Self-heal: .env files written by older versions of this script hold a random
# hex NEW_COOKIE_KEY that the entrypoint (and Defuse) rejects.
if ! php -r 'require $argv[1]; Defuse\Crypto\Key::loadFromAsciiSafeString($argv[2]);' \
    "$DEFUSE_PHAR" "$(grep -E '^NEW_COOKIE_KEY=' .env | cut -d= -f2-)" 2>/dev/null; then
    echo "Regenerating invalid NEW_COOKIE_KEY in .env"
    sed -i "s|^NEW_COOKIE_KEY=.*|NEW_COOKIE_KEY=$(make_cookie_key)|" .env
fi

# 3. Validate, build and start the stack.
"${COMPOSE[@]}" config -q
"${COMPOSE[@]}" up -d --build

# 4. Verify the seed data actually imported (db healthcheck only proves
#    connectivity, not data). If tables are missing, the seed was mounted
#    empty (e.g. a prior boot created the db volume before this script ran).
DB_PASSWD=$(grep -E '^DB_PASSWD=' .env | cut -d= -f2-)
if [ -n "$DB_PASSWD" ] && ! "${COMPOSE[@]}" exec -T db \
    mariadb -u"${DB_NAME:-qloapps}" -p"$DB_PASSWD" "${DB_NAME:-qloapps}" \
    -e "SHOW TABLES LIKE '${DB_PREFIX:-qlo_}shop_url'" 2>/dev/null | grep -q shop_url; then
    echo "WARNING: seed data is missing from the database." >&2
    echo "A pre-existing empty db volume is shadowing the init mount. Fix with:" >&2
    echo "  docker compose -f docker-compose.yml -f docker-compose.codespaces.yml down -v" >&2
    echo "  bash scripts/deploy-codespaces.sh" >&2
    exit 1
fi

# 4. Wait for the web service to become healthy.
WEB_ID=$("${COMPOSE[@]}" ps -q web 2>/dev/null || true)
if [ -n "$WEB_ID" ]; then
    for _ in $(seq 1 60); do
        if [ "$(docker inspect -f '{{.State.Health.Status}}' "$WEB_ID" 2>/dev/null)" = "healthy" ]; then
            break
        fi
        sleep 5
    done
fi

"${COMPOSE[@]}" ps

echo "Demo ready: http://localhost:8080"
echo "Admin:      http://localhost:8080/hotel-admin"
echo
echo "To share: open the Ports panel in Codespaces, hover port 8080 and set it to Public."
echo "To refresh after 'git pull': re-run this script (rebuilds the image with new code)."
