#!/usr/bin/env bash
# Boots the QloApps demo stack inside a GitHub Codespace.
# Idempotent: safe to re-run after `git pull` to refresh the demo.
# Usage: bash scripts/deploy-codespaces.sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

COMPOSE=(docker compose -f docker-compose.yml -f docker-compose.codespaces.yml)

if ! command -v docker >/dev/null 2>&1; then
    echo "docker is not available in this Codespace." >&2
    exit 1
fi

# 1. Make the MariaDB 11.x seed dump compatible with the pinned mariadb:10.11
#    image (utf8mb3_uca1400_ai_ci does not exist on 10.11). The tracked
#    db/init file is left untouched; the converted copy lives in /tmp.
INIT_SRC=db/init/01-init.sql
INIT_DST=/tmp/qlo-init-converted/01-init.sql
if [ ! -f "$INIT_SRC" ]; then
    echo "Missing seed dump: $INIT_SRC. Push it to the repo first." >&2
    exit 1
fi
mkdir -p "$(dirname "$INIT_DST")"
sed -e 's/utf8mb4_uca1400_ai_ci/utf8mb4_general_ci/g' \
    -e 's/utf8mb3_uca1400_ai_ci/utf8mb3_general_ci/g' \
    "$INIT_SRC" > "$INIT_DST"
if grep -q uca1400 "$INIT_DST"; then
    echo "Collation conversion incomplete; aborting." >&2
    exit 1
fi

# 2. Generate .env on first run. Never commit it.
if [ ! -f .env ]; then
    cat > .env <<EOF
# Generated by scripts/deploy-codespaces.sh - local to this Codespace only.
DB_NAME=qloapps
DB_USER=qloapps
DB_PASSWD=$(openssl rand -hex 12)
MARIADB_ROOT_PASSWORD=$(openssl rand -hex 12)
DB_PREFIX=qlo_
HTTP_PORT=8080
SHOP_DOMAIN=localhost:8080
COOKIE_KEY=$(openssl rand -hex 24)
COOKIE_IV=$(openssl rand -hex 4)
NEW_COOKIE_KEY=$(openssl rand -hex 24)
EOF
fi

# 3. Validate, build and start the stack.
"${COMPOSE[@]}" config -q
"${COMPOSE[@]}" up -d --build

# 4. Wait for the web service to become healthy.
WEB_ID=$("${COMPOSE[@]}" ps -q web 2>/dev/null || true)
if [ -n "$WEB_ID" ]; then
    for _ in $(seq 1 60); do
        if [ "$(docker inspect -f '{{.State.Health.Status}}' "$WEB_ID" 2>/dev/null)" = "healthy" ]; then
            break
        fi
        sleep 5
    done
fi

"${COMPOSE[@]}" ps

echo
echo "Demo ready: http://localhost:8080"
echo "Admin:      http://localhost:8080/hotel-admin"
echo
echo "To share: open the Ports panel in Codespaces, hover port 8080 and set it to Public."
echo "To refresh after 'git pull': re-run this script (rebuilds the image with new code)."
